In [47]:
import torch

### Pytorch is librarary for processing tensors a tensor can be a number, vector, matrix or any n-dimensional array.

In [48]:
t1=torch.tensor(4.0)
t1

tensor(4.)

In [49]:
t1.dtype

torch.float32

In [50]:
t2=torch.tensor([1.0,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [51]:
t2.dtype

torch.float32

In [52]:
t3=torch.tensor([[5.0,6],
                 [7,8],
                 [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [53]:
t4=torch.tensor([[[1.0,2,3],
                 [4,5,6],
                 [7,8,9]],
                 [[10.,11,12],
                  [11,12,13],
                  [14,15,16]]])
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [11., 12., 13.],
         [14., 15., 16.]]])

In [54]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [55]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [56]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [57]:
print(t4)
t4.shape

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [11., 12., 13.],
         [14., 15., 16.]]])


torch.Size([2, 3, 3])

In [63]:
x=torch.tensor(3.0,requires_grad=True)
w=torch.tensor(4.,requires_grad=True) # for automatic grdiants
b=torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3., requires_grad=True),
 tensor(4., requires_grad=True),
 tensor(5., requires_grad=True))

In [64]:
#arthmetic operations
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [65]:
y.backward()# gives the derivative of y

In [66]:
print('dy/dx',x.grad) 
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx tensor(4.)
dy/dw tensor(3.)
dy/db tensor(1.)


The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

In [67]:
t6=torch.full((3,2),7)
t6

tensor([[7, 7],
        [7, 7],
        [7, 7]])

In [72]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [71]:
t7=torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [ 7.,  7.],
        [ 7.,  7.],
        [ 7.,  7.]])

In [74]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [ 0.6570,  0.6570],
        [ 0.6570,  0.6570],
        [ 0.6570,  0.6570]])

In [76]:
t9=t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [ 0.6570,  0.6570]],

        [[ 0.6570,  0.6570],
         [ 0.6570,  0.6570]]])

 Numpy is a popular open source library used for mathmitical computing , it enables effiecnt operation on large multi dimennsional array, and has large ecosystem for supporting librearis:
 matplotlib for plotting and visualization
 OpenCV for image and video processing
 pandas for file i/o and data analysis 

pytorch exploits this existing ecosystems 

In [82]:
import numpy as np

x=np.array([[1,2],
            [4,5.0]])
x

array([[1., 2.],
       [4., 5.]])

In [83]:
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [4., 5.]], dtype=torch.float64)

In [84]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [85]:
z=y.numpy()
z

array([[1., 2.],
       [4., 5.]])

the interoperability between numpy and tensor are essintial because morst datasaets we will work on will be on  numpy

Then why pytroch is required?
pytroch is essintal for mainly two reasons:

1.autograd: the ability to automatically compute gradiants for tensor operaations is essential for trainin deep learning models.
2.gpu support: pytrorch tensor operations can perfomed more efficantly on gpus 